
package beershowcase;

import beershowcase.beerdata.BeerKnowledge;

/**
 *
 * @author Grzegorz Łoś
 */
public class BeersManagementPane extends javax.swing.JPanel {

    BeerKnowledge beerKnowledge;
    /**
     * Creates new form BeersManagementPane
     */
    public BeersManagementPane(BeerKnowledge beerKnowledge) {
        this.beerKnowledge = beerKnowledge;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addBeerButton = new javax.swing.JButton();

        addBeerButton.setText("Add beer");
        addBeerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBeerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addBeerButton)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addBeerButton)
                .addContainerGap(263, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBeerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBeerButtonActionPerformed
        addBeerClicked();
    }//GEN-LAST:event_addBeerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBeerButton;
    // End of variables declaration//GEN-END:variables

    private void addBeerClicked() {
        EditBeerDialog editBeerDialog = new EditBeerDialog(RunningApplication.MainFrame, beerKnowledge);
        editBeerDialog.setVisible(true);
        if (editBeerDialog.isConfirmed()) {
            editBeerDialog.fill(beerKnowledge.makeBeer());
        }
    }
    
    void reset(BeerKnowledge beerKnowledge) {
        this.beerKnowledge = beerKnowledge;
        //breweriesTable.reset(beerKnowledge);
        repaint();
        revalidate();
    }
}
