
package beershowcase;

import beershowcase.beerdata.Beer;
import beershowcase.beerdata.Brewery;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/**
 *
 * @author Grzegorz Łoś
 */
public class BeerViewPanel extends javax.swing.JPanel {

    private final Beer beer;
    private final Brewery brewery;
    
    /**
     * Creates new form BeerViewPanel
     */
    public BeerViewPanel(Beer beer, Brewery brewery) {
        this.beer = beer;
        this.brewery = brewery;
        initComponents();
        beerNameLabel.setText(htmledString(beer.getName()));
        styleLabel.setText(htmledString(beer.getDeclaredStyle()));
        breweryNameLabel.setText(htmledString(brewery.getName()));
        description.setText(beer.getDescritpion());
        setBreweryLogo();
        setBeerImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        beerNameLabel = new javax.swing.JLabel();
        styleLabel = new javax.swing.JLabel();
        breweryNameLabel = new javax.swing.JLabel();
        breweryLogoLabel = new javax.swing.JLabel();
        beerImageLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();

        beerNameLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        beerNameLabel.setText("Unknown name");

        styleLabel.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        styleLabel.setText("<html>Unknown style</html>");

        breweryNameLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        breweryNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        breweryNameLabel.setText("Unknown brewery");

        breweryLogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        breweryLogoLabel.setText("jLabel3");

        beerImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        beerImageLabel.setText("jLabel1");

        jLabel1.setText("Description");

        description.setEditable(false);
        description.setColumns(20);
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(beerNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(styleLabel))
                        .addGap(0, 159, Short.MAX_VALUE))
                    .addComponent(beerImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(breweryLogoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(breweryNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(breweryNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(breweryLogoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(styleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(beerImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel beerImageLabel;
    private javax.swing.JLabel beerNameLabel;
    private javax.swing.JLabel breweryLogoLabel;
    private javax.swing.JLabel breweryNameLabel;
    private javax.swing.JTextArea description;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel styleLabel;
    // End of variables declaration//GEN-END:variables

    private String htmledString(String text) {
        return "<html>" + text + "</html>";
    }

    private void setBreweryLogo() {
        BufferedImage image = brewery.getLogo();
        if (image == null) {
            breweryLogoLabel.setIcon(null);
            breweryLogoLabel.setText("No logo");
        } else {
            breweryLogoLabel.setIcon(new ImageIcon(image));
            breweryLogoLabel.setText("");
        }
    }

    private void setBeerImage() {
        BufferedImage image = beer.getBottleImage();
        if (image == null)
            image = beer.getLabelImage();
        
        if (image == null) {
            beerImageLabel.setIcon(null);
            beerImageLabel.setText("No picture");
        } else {
            beerImageLabel.setIcon(new ImageIcon(image));
            beerImageLabel.setText("");
        }
    }
}
