
package beershowcase;

import beershowcase.beerdata.Beer;
import beershowcase.beerdata.BeerKnowledge;
import beershowcase.beerdata.filters.Filter;
import java.awt.BorderLayout;
import java.util.ArrayList;

/**
 *
 * @author Grzegorz Łoś
 */
public class BeerShowcasePane extends javax.swing.JPanel {
    
    private final BeerKnowledge beerKnowledge;
    private final ParamSelectionPanel paramSelectionPanel;
    private final BeerBrowserPanel beerBrowserPanel;
    
    /**
     * Creates new form BeerShowcasePane
     */
    public BeerShowcasePane(BeerKnowledge beerKnowledge) {
        this.beerKnowledge = beerKnowledge;
        initComponents();
        setLayout(new BorderLayout());
        paramSelectionPanel = new ParamSelectionPanel(this);
        beerBrowserPanel = new BeerBrowserPanel(this, beerKnowledge);
        add(paramSelectionPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    void goToBrowsingMode() {
        removeAll();
        
        Filter filter = paramSelectionPanel.buildFilter();
        ArrayList<Beer> beers = beerKnowledge.getBeers(filter);
        beerBrowserPanel.setBeers(beers);
        
        add(beerBrowserPanel);
        repaint();
        revalidate();
    }
    
    void goToSelectionMode() {
        removeAll();
        add(paramSelectionPanel);
        repaint();
        revalidate();
    }

}
