
package beershowcase.gui;

import beershowcase.beerdata.Beer;
import beershowcase.beerdata.Brewery;
import beershowcase.gui.components.AutoLabel;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.image.BufferedImage;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Grzegorz Łoś
 */
public class BeerViewPanelOld extends javax.swing.JPanel {

    private final Beer beer;
    private final Brewery brewery;
    
    /**
     * Creates new form BeerViewPanel
     */
    public BeerViewPanelOld(Beer beer, Brewery brewery) {
        this.beer = beer;
        this.brewery = brewery;
        initComponents();
        beerNameLabel.setText(htmledString(beer.getName()));
        styleLabel.setText(htmledString(beer.getDeclaredStyle()));
        breweryNameLabel.setText(htmledString(brewery.getName()));
        description.setText(beer.getDescritpion(RunningApplication.getFileSystem()));
        priceLabel.setText(beer.getPrice().toString());
        paramsContainer.setLayout(new BorderLayout());
        paramsContainer.add(makeParamsPanel());
        imagePanelContainer.setLayout(new BorderLayout());
        logoContainer.setLayout(new BorderLayout());
        setBreweryLogo();
        setBeerImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        beerNameLabel = new javax.swing.JLabel();
        styleLabel = new javax.swing.JLabel();
        breweryNameLabel = new javax.swing.JLabel();
        imagePanelContainer = new javax.swing.JPanel();
        logoContainer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        paramsContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();

        beerNameLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        beerNameLabel.setText("Unknown name");

        styleLabel.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        styleLabel.setText("<html>Unknown style</html>");

        breweryNameLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        breweryNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        breweryNameLabel.setText("Unknown brewery");

        imagePanelContainer.setMaximumSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout imagePanelContainerLayout = new javax.swing.GroupLayout(imagePanelContainer);
        imagePanelContainer.setLayout(imagePanelContainerLayout);
        imagePanelContainerLayout.setHorizontalGroup(
            imagePanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        imagePanelContainerLayout.setVerticalGroup(
            imagePanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        logoContainer.setMaximumSize(new java.awt.Dimension(150, 150));
        logoContainer.setMinimumSize(new java.awt.Dimension(50, 50));
        logoContainer.setPreferredSize(new java.awt.Dimension(100, 100));
        logoContainer.setRequestFocusEnabled(false);

        javax.swing.GroupLayout logoContainerLayout = new javax.swing.GroupLayout(logoContainer);
        logoContainer.setLayout(logoContainerLayout);
        logoContainerLayout.setHorizontalGroup(
            logoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        logoContainerLayout.setVerticalGroup(
            logoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Price:");

        priceLabel.setText("jLabel3");

        paramsContainer.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout paramsContainerLayout = new javax.swing.GroupLayout(paramsContainer);
        paramsContainer.setLayout(paramsContainerLayout);
        paramsContainerLayout.setHorizontalGroup(
            paramsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        paramsContainerLayout.setVerticalGroup(
            paramsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        description.setEditable(false);
        description.setBackground(this.getBackground());
        description.setColumns(20);
        description.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        description.setLineWrap(true);
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(beerNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                        .addComponent(styleLabel))
                    .addComponent(imagePanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(breweryNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(paramsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(logoContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(breweryNameLabel)
                    .addComponent(jLabel2)
                    .addComponent(priceLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(styleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imagePanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logoContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(paramsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel beerNameLabel;
    private javax.swing.JLabel breweryNameLabel;
    private javax.swing.JTextArea description;
    private javax.swing.JPanel imagePanelContainer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel logoContainer;
    private javax.swing.JPanel paramsContainer;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel styleLabel;
    // End of variables declaration//GEN-END:variables

    private String htmledString(String text) {
        return "<html>" + text + "</html>";
    }

    private void setBreweryLogo() {
        BufferedImage image = brewery.getLogo(RunningApplication.getFileSystem());
        Component comp;
        if (image == null) {
            comp = new JLabel("No logo");
        } else {
            comp = new ImagePanel(image);
        }
        logoContainer.add(comp);
    }

    private void setBeerImage() {
        BufferedImage image = beer.getLabelImage(RunningApplication.getFileSystem());
        
        Component comp;
        if (image == null) {
            comp = new JLabel("No picture");
        } else {
            comp = new ImagePanel(image);
        }
        imagePanelContainer.add(comp);
    }
    
    private Component makeParamsPanel() {
        JPanel panel = new JPanel(new GridLayout(3, 2));
        
        /*panel.add(new AutoLabel("Gravity:", JLabel.RIGHT));
        panel.add(new AutoLabel(beer.getPlato().toString() + "\u00B0Blg", JLabel.LEFT));
        
        panel.add(new AutoLabel("Alc. vol.:", JLabel.RIGHT));
        panel.add(new AutoLabel(beer.getAbv().toString() + "%", JLabel.LEFT));
        
        panel.add(new AutoLabel("IBU:", JLabel.RIGHT));
        panel.add(new AutoLabel("" + beer.getIbu(), JLabel.LEFT));*/
        
        return panel;
    }
}
