
package beershowcase.gui;

import beershowcase.beerdata.Beer;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Logger;

/**
 *
 * @author grzes
 */
public class BeerBrowserPanel extends javax.swing.JPanel
        implements Beer.ChangeListener {
    private ArrayList<Beer> displayed = new ArrayList<>();
    private final HashMap<Integer, BeerViewPanel> beerViews = new HashMap<>();
    private int index = 0;
    
    private static final Logger LOGGER = Logger.getLogger(BeerBrowserPanel.class.getName());
    
    /**
     * Creates new form BeerBrowserPanel
     */
    public BeerBrowserPanel() {
        initComponents();
        beerViewContainer.setLayout(new BorderLayout());
        setBeerView();
        setButtonAvailability();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nextButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        beerViewContainer = new javax.swing.JPanel();
        noResultsLabel = new javax.swing.JLabel();
        prevButton = new javax.swing.JButton();

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        beerViewContainer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        noResultsLabel.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        noResultsLabel.setText("<html>No beers met the selected criteria.</html>");

        javax.swing.GroupLayout beerViewContainerLayout = new javax.swing.GroupLayout(beerViewContainer);
        beerViewContainer.setLayout(beerViewContainerLayout);
        beerViewContainerLayout.setHorizontalGroup(
            beerViewContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beerViewContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noResultsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        beerViewContainerLayout.setVerticalGroup(
            beerViewContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beerViewContainerLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(noResultsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(320, Short.MAX_VALUE))
        );

        prevButton.setText("Prev");
        prevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(filler1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(filler2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prevButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beerViewContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(filler3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(filler4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(nextButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nextButton, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(prevButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler3, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(beerViewContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        if (index < displayed.size() - 1)
            index++;
        setBeerView();
        setButtonAvailability();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButtonActionPerformed
        if (index > 0)
            index--;
        setBeerView();
        setButtonAvailability();
    }//GEN-LAST:event_prevButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel beerViewContainer;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel noResultsLabel;
    private javax.swing.JButton prevButton;
    // End of variables declaration//GEN-END:variables

    public void setDisplayedBeers(ArrayList<Beer> beers) {
        clean();
        displayed = beers;
        index = 0;
        buildBeerViews();
        setButtonAvailability();
        setBeerView();
    }
    
    private void clean() {
        for (Beer b: displayed)
            b.removeChangeListener(this);
        displayed.clear();
        beerViews.clear();
    }
    
    private void buildBeerViews() {
        for (Beer beer: displayed) {
            buildBeerView(beer);
        }
    }
    
    private void buildBeerView(Beer beer) {
        BeerViewPanel beerViewPanel = new BeerViewPanel(
                beer, RunningApplication.getBeerKnowledge().getBreweryOfBeer(beer));
        beerViews.put(beer.getId(), beerViewPanel);      
        beer.addChangeListener(this);
    }
    
    private void setBeerView() {
        beerViewContainer.removeAll();
        if (displayed.isEmpty()) {
            beerViewContainer.add(noResultsLabel);
        } else {
            Beer beer = displayed.get(index);
            BeerViewPanel beerViewPanel = beerViews.get(beer.getId());
            beerViewContainer.add(beerViewPanel);
        }        
        revalidate();
        repaint();
    }

    private void setButtonAvailability() {
        nextButton.setEnabled(index < displayed.size() - 1);
        prevButton.setEnabled(index > 0);            
    }


    @Override
    public void beerEdited(Beer.EditionEvent event) {
        Beer beer = event.source;
        buildBeerView(beer);
        setBeerView();
    }

    void addBeer(Beer beer) {
        displayed.add(beer);
        buildBeerView(beer);
    }

    void showBeer(Beer beer) {
        for (int i = 0; i < displayed.size(); ++i) {
            if (displayed.get(i) == beer) {
                index = i;
                setBeerView();
                setButtonAvailability();
                break;
            }
        }
    }

    public Beer getCurrBeer() {
        if (displayed.isEmpty())
            return null;
        else
            return displayed.get(index);
    }
}
           
