
package beershowcase.gui;

import beershowcase.beerdata.Beer;
import beershowcase.beerdata.BeerProperties;
import beershowcase.beerdata.Brewery;
import beershowcase.utils.FixedPointReal;
import beershowcase.beerdata.StyleKeyword;
import beershowcase.beerdata.autostyle.StyleFinder;
import beershowcase.beerdata.autostyle.simple.SimpleStyleFinder;
import beershowcase.external.ExternalSource;
import beershowcase.external.ExternalSourceDispatcher;
import beershowcase.utils.Box;
import java.awt.BorderLayout;
import java.awt.image.BufferedImage;
import java.util.Collection;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Grzegorz Łoś
 */
public class EditBeerDialog extends javax.swing.JDialog {
    private final AllKeywordsPanel keywordsPanel = new AllKeywordsPanel();
    private final SelectImagePanel labelImageSelector = new SelectImagePanel();
    private boolean confirmed;
    private Brewery selectedBrewery;
    private final StyleFinder styleFinder = new SimpleStyleFinder();
    private final ExternalSource external = new ExternalSourceDispatcher();
    
    /**
     * Creates new form EditBeerDialog
     */
    public EditBeerDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        
        setTitle("Add a new beer");
        keywordsContainer.setLayout(new BorderLayout());
        keywordsContainer.add(new JScrollPane(keywordsPanel));
        labelSelectorContainer.setLayout(new BorderLayout());
        labelSelectorContainer.add(labelImageSelector);
    }

    EditBeerDialog(java.awt.Frame parent, Beer beer) {
        super(parent, true);
        initComponents();
        
        setTitle("Edit a beer");
        keywordsContainer.setLayout(new BorderLayout());
        keywordsContainer.add(new JScrollPane(keywordsPanel));
        labelSelectorContainer.setLayout(new BorderLayout());
        labelSelectorContainer.add(labelImageSelector);
        
        setDataFrom(beer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        breweryField = new javax.swing.JTextField();
        selectBreweryButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        styleField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        availableBox = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        priceSpinner = new javax.swing.JSpinner();
        priceKnown = new javax.swing.JCheckBox();
        novelty = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        blgSpinner = new javax.swing.JSpinner();
        abvSpinner = new javax.swing.JSpinner();
        ibuSpinner = new javax.swing.JSpinner();
        blgKnown = new javax.swing.JCheckBox();
        abvKnown = new javax.swing.JCheckBox();
        ibuKnown = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        keywordsContainer = new javax.swing.JPanel();
        imagesPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        labelSelectorContainer = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setText("Beer basic information");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setLabelFor(nameField);
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Brewery:");

        breweryField.setEditable(false);
        breweryField.setText("Select brewery by clicking a button on the right...");

        selectBreweryButton.setText("Select");
        selectBreweryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBreweryButtonActionPerformed(evt);
            }
        });

        description.setColumns(20);
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Description:");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Declared style:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Store"));

        availableBox.setSelected(true);
        availableBox.setText("Available");
        availableBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableBoxActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Price:");

        priceSpinner.setModel(new SpinnerNumberModel(0.0, 0.0, 1000.0, 0.1));
        priceSpinner.setEnabled(false);

        priceKnown.setText("Set price");
        priceKnown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceKnownActionPerformed(evt);
            }
        });

        novelty.setText("Novelty");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(priceKnown)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(availableBox)
                .addGap(33, 33, 33)
                .addComponent(novelty)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availableBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(novelty))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(priceKnown)
                .addContainerGap())
        );

        jButton1.setText("Auto fill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Alc. vol.:");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Blg:");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("IBU:");

        blgSpinner.setModel(new SpinnerNumberModel(0.0, 0.0, 100.0, 0.1));
        blgSpinner.setEnabled(false);

        abvSpinner.setModel(new SpinnerNumberModel(0.0, 0.0, 100.0, 0.1));
        abvSpinner.setEnabled(false);

        ibuSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 200, 1));
        ibuSpinner.setEnabled(false);

        blgKnown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blgKnownActionPerformed(evt);
            }
        });

        abvKnown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abvKnownActionPerformed(evt);
            }
        });

        ibuKnown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ibuKnownActionPerformed(evt);
            }
        });

        jLabel12.setText("Parameters:");

        jLabel13.setText("is known?");

        jLabel14.setText("value");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(24, 24, 24)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(styleField)
                                    .addComponent(nameField)))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addGap(0, 2, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(breweryField, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectBreweryButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(34, 34, 34)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(blgKnown)
                                            .addComponent(abvKnown)
                                            .addComponent(ibuKnown))
                                        .addGap(38, 38, 38))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(17, 17, 17)))
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ibuSpinner)
                                    .addComponent(blgSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(abvSpinner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel14)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, 4, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(styleField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(breweryField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectBreweryButton))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLabel12))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addComponent(blgSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(abvSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addComponent(blgKnown)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(abvKnown)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ibuKnown)
                                            .addComponent(ibuSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        tabbedPane.addTab("Main", mainPanel);

        javax.swing.GroupLayout keywordsContainerLayout = new javax.swing.GroupLayout(keywordsContainer);
        keywordsContainer.setLayout(keywordsContainerLayout);
        keywordsContainerLayout.setHorizontalGroup(
            keywordsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );
        keywordsContainerLayout.setVerticalGroup(
            keywordsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Tags", keywordsContainer);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel7.setText("Select label image");

        labelSelectorContainer.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout labelSelectorContainerLayout = new javax.swing.GroupLayout(labelSelectorContainer);
        labelSelectorContainer.setLayout(labelSelectorContainerLayout);
        labelSelectorContainerLayout.setHorizontalGroup(
            labelSelectorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );
        labelSelectorContainerLayout.setVerticalGroup(
            labelSelectorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout imagesPanelLayout = new javax.swing.GroupLayout(imagesPanel);
        imagesPanel.setLayout(imagesPanelLayout);
        imagesPanelLayout.setHorizontalGroup(
            imagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagesPanelLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 499, Short.MAX_VALUE))
            .addGroup(imagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(labelSelectorContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        imagesPanelLayout.setVerticalGroup(
            imagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagesPanelLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 491, Short.MAX_VALUE))
            .addGroup(imagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(labelSelectorContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Picture", imagesPanel);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton)
                .addContainerGap())
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 547, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        cancelClicked();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        okClicked();
    }//GEN-LAST:event_okButtonActionPerformed

    private void selectBreweryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBreweryButtonActionPerformed
        selectBrewerClicked();
    }//GEN-LAST:event_selectBreweryButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        autoFill();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void blgKnownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blgKnownActionPerformed
        blgSpinner.setEnabled(blgKnown.isSelected());
    }//GEN-LAST:event_blgKnownActionPerformed

    private void abvKnownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abvKnownActionPerformed
        abvSpinner.setEnabled(abvKnown.isSelected());
    }//GEN-LAST:event_abvKnownActionPerformed

    private void ibuKnownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ibuKnownActionPerformed
        ibuSpinner.setEnabled(ibuKnown.isSelected());
    }//GEN-LAST:event_ibuKnownActionPerformed

    private void priceKnownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceKnownActionPerformed
        priceSpinner.setEnabled(priceKnown.isSelected());
    }//GEN-LAST:event_priceKnownActionPerformed

    private void availableBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availableBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox abvKnown;
    private javax.swing.JSpinner abvSpinner;
    private javax.swing.JCheckBox availableBox;
    private javax.swing.JCheckBox blgKnown;
    private javax.swing.JSpinner blgSpinner;
    private javax.swing.JTextField breweryField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextArea description;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JCheckBox ibuKnown;
    private javax.swing.JSpinner ibuSpinner;
    private javax.swing.JPanel imagesPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel keywordsContainer;
    private javax.swing.JPanel labelSelectorContainer;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nameField;
    private javax.swing.JCheckBox novelty;
    private javax.swing.JButton okButton;
    private javax.swing.JCheckBox priceKnown;
    private javax.swing.JSpinner priceSpinner;
    private javax.swing.JButton selectBreweryButton;
    private javax.swing.JTextField styleField;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables

    private void cancelClicked() {
        confirmed = false;
        dispose();
    }

    public void fill(Beer newBeer) {
        newBeer.setBreweryId(selectedBrewery.getId());
        newBeer.setAvailable(availableBox.isSelected());
        newBeer.setNovelty(novelty.isSelected());
        newBeer.setName(nameField.getText().trim());
        newBeer.setDeclaredStyle(styleField.getText());
        if (priceKnown.isSelected())
            newBeer.setPrice(new FixedPointReal((Double) priceSpinner.getValue(), 2));
        if (blgKnown.isSelected())
            newBeer.setPlato(new FixedPointReal((Double) blgSpinner.getValue(), 1));
        if (abvKnown.isSelected())
            newBeer.setAbv(new FixedPointReal((Double) abvSpinner.getValue(), 1));
        if (ibuKnown.isSelected())
            newBeer.setIbu(new FixedPointReal((long) ((Integer) ibuSpinner.getValue()), 0));
        newBeer.addStyleKeywords(keywordsPanel.getSelectedKeywords());
        newBeer.setDescritpion(description.getText());
        newBeer.setLabelImage(labelImageSelector.getImage());
    }

    private void okClicked() {
        if (nameField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Beer name cannot be left empty.",
                    "No name", JOptionPane.INFORMATION_MESSAGE);
            return ;
        }
        if (selectedBrewery == null) {
            JOptionPane.showMessageDialog(this, "You must select a brewery.",
                    "No name", JOptionPane.INFORMATION_MESSAGE);
            return ;
        }
        
        confirmed = true;
        dispose();
    }

    public boolean isConfirmed() {
        return confirmed;
    }

    private void selectBrewerClicked() {
        SelectBreweryDialog selectBreweryDialog = new SelectBreweryDialog(
                RunningApplication.MainFrame);
        selectBreweryDialog.setLocationRelativeTo(this);
        selectBreweryDialog.setVisible(true);
        Brewery br = selectBreweryDialog.getSelectedBrewery();
        if (br != null) {
            selectedBrewery = br;
            breweryField.setText(selectedBrewery.getName());
        }
    }

    private void setDataFrom(Beer beer) {
        nameField.setText(beer.getName());
        selectedBrewery = RunningApplication.getBeerKnowledge().getBreweryOfBeer(beer);
        breweryField.setText(selectedBrewery != null ? selectedBrewery.getName() : "?");
        styleField.setText(beer.getDeclaredStyle());
        description.setText("" + beer.getDescritpion(RunningApplication.getFileSystem()));
        Box<BufferedImage> beerImage = beer.getLabelImage(RunningApplication.getFileSystem());
        if (!beerImage.isEmpty())
            labelImageSelector.setInitialImage(beerImage.getValue());
        availableBox.setSelected(beer.isAvailable());
        keywordsPanel.setSelectedKeywords(beer.getStyleKeywords());
        novelty.setSelected(beer.isNovelty());
        
        setComponentFromBox(beer.getPlato(), blgKnown, blgSpinner);
        setComponentFromBox(beer.getAbv(), abvKnown, abvSpinner);
        setComponentFromBox(beer.getIbu(), ibuKnown, ibuSpinner);
        setComponentFromBox(beer.getPrice(), priceKnown, priceSpinner);     
    }
    
    private void setDataFrom(BeerProperties props) {
        nameField.setText(props.name);
        selectedBrewery = RunningApplication.getBeerKnowledge().getBreweryByName(props.breweryName);
        breweryField.setText(selectedBrewery != null ? selectedBrewery.getName() : "?");
        styleField.setText(props.declaredStyle);
        description.setText(props.descritpion);
        labelImageSelector.setInitialImage(props.labelImage);
        
        setComponentFromValue(props.plato, blgKnown, blgSpinner);
        setComponentFromValue(props.abv, abvKnown, abvSpinner);
        setComponentFromValue(props.ibu, ibuKnown, ibuSpinner);
        
        autoselectKeywords(props.declaredStyle);
    }
    
    private void setComponentFromBox(Box<FixedPointReal> box, JCheckBox isKnown, JSpinner spinner) {
        setComponentFromValue(box.isEmpty() ? null : box.getValue(), isKnown, spinner);
    }
    private void setComponentFromValue(FixedPointReal value, JCheckBox isKnown, JSpinner spinner) {
        isKnown.setSelected(value != null);
        spinner.setEnabled(value != null);
        if (value != null)
            spinner.setValue(value.getDoubleValue());
    }

    private void autoselectKeywords(String declaredStyle) {
        Collection<StyleKeyword> keywords = styleFinder.findStyleKeywords(declaredStyle);
        keywordsPanel.setSelectedKeywords(keywords);
    }

    private void autoFill() {
        String address = JOptionPane.showInputDialog(rootPane,
                "Paste address of the webpage storing beer's data",
                "Input a web address", JOptionPane.QUESTION_MESSAGE);
        if (address != null) {
            new HeavyOperation("Fetching data from external source") {
                @Override
                protected void timeConsumingTask() {
                    BeerProperties props = external.readFrom(address);
                    handleFetchedProperties(props);
                }
                
            }.execute();
        }
    }

    private void handleFetchedProperties(BeerProperties props) {
        if (props == null) {
            JOptionPane.showMessageDialog(rootPane, "Provided address was invalid",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return ;
        }
        setDataFrom(props);
    }
}
