
package beershowcase.gui;

/**
 *
 * @author grzes
 */
public class ManagementPane extends javax.swing.JPanel {
    BreweriesManagementPane breweriesManagementPane = new BreweriesManagementPane();
    BeersManagementPane beersManagementPane = new BeersManagementPane();
    
    /**
     * Creates new form BeerManagementPane
     */
    public ManagementPane() {
        initComponents();
        tabbedPane.setComponentAt(0, beersManagementPane);
        tabbedPane.setComponentAt(1, breweriesManagementPane);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        breweriesContainer = new javax.swing.JPanel();
        beersContainer = new javax.swing.JPanel();

        javax.swing.GroupLayout breweriesContainerLayout = new javax.swing.GroupLayout(breweriesContainer);
        breweriesContainer.setLayout(breweriesContainerLayout);
        breweriesContainerLayout.setHorizontalGroup(
            breweriesContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        breweriesContainerLayout.setVerticalGroup(
            breweriesContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Beers", breweriesContainer);

        javax.swing.GroupLayout beersContainerLayout = new javax.swing.GroupLayout(beersContainer);
        beersContainer.setLayout(beersContainerLayout);
        beersContainerLayout.setHorizontalGroup(
            beersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        beersContainerLayout.setVerticalGroup(
            beersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Breweries", beersContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel beersContainer;
    private javax.swing.JPanel breweriesContainer;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables

   
    /**
     * Notify ManagementPane that BeerKnowledge object has been changed.
     */
    public void reset() {
        breweriesManagementPane.reset();
        beersManagementPane.reset();
    }
}
