
package beershowcase.gui;

import beershowcase.beerdata.StyleKeyword;
import beershowcase.beerdata.filters.Conjunction;
import beershowcase.beerdata.filters.Filter;
import beershowcase.beerdata.filters.StyleFilter;
import java.awt.BorderLayout;
import java.util.Collection;

/**
 *
 * @author Grzegorz Łoś
 */
public class ParamSelectionPanel extends javax.swing.JPanel {

    private final AllKeywordsPanel stylesPanel = new AllKeywordsPanel();
    private final BeerShowcasePane beerShowcasePane;
    /**
     * Creates new form ParamSelectionPanel
     */
    public ParamSelectionPanel(BeerShowcasePane beerShowcasePane) {
        this.beerShowcasePane = beerShowcasePane;
        initComponents();
        stylesPanelContainer.setLayout(new BorderLayout());
        stylesPanelContainer.add(stylesPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stylesPanelContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        stylesPanelContainer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout stylesPanelContainerLayout = new javax.swing.GroupLayout(stylesPanelContainer);
        stylesPanelContainer.setLayout(stylesPanelContainerLayout);
        stylesPanelContainerLayout.setHorizontalGroup(
            stylesPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        stylesPanelContainerLayout.setVerticalGroup(
            stylesPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        jLabel1.setText("Select beer criteria");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(261, Short.MAX_VALUE))
            .addComponent(stylesPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stylesPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        resetClicked();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        searchClicked();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton resetButton;
    private javax.swing.JPanel stylesPanelContainer;
    // End of variables declaration//GEN-END:variables

    private void resetClicked() {
        stylesPanel.reset();
        revalidate();
        repaint();
    }

    private void searchClicked() {
        beerShowcasePane.goToBrowsingMode();
    }

    Filter buildFilter() {
        Conjunction f = new Conjunction();
        Collection<StyleKeyword> keywords = stylesPanel.getSelectedKeywords();
        for (StyleKeyword keyword: keywords)
            f.add(new StyleFilter(keyword));
        return f;        
    }
}
